version: "3.8"

services:
  pose_app:
    build:
      context: ../
      dockerfile: deployment/Dockerfile
    ports:
      - "7860:7860"  # Map Gradio app port
      - "8000:8000"  # Map Prometheus metrics port
    networks:
      - app_network
    volumes:
      - ../src/models:/app/models  # Ensure models are accessible
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:7860 || exit 1"]  # Check Gradio app
      interval: 30s  # Check every 30 seconds
      timeout: 20s    # Mark as failed if it doesn't respond in 20 seconds
      retries: 5     # Fail if 5 consecutive checks fail

  prometheus:
    image: prom/prometheus
    volumes:
      - ../monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"  # Prometheus UI
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9090 || exit 1"]  # Check Prometheus
      interval: 30s
      timeout: 20s
      retries: 5

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"  # Grafana UI
    networks:
      - app_network
    volumes:
      - grafana_data:/var/lib/grafana
      - ../monitoring/grafana:/etc/grafana/provisioning
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]  # Check Grafana
      interval: 30s
      timeout: 20s
      retries: 5

volumes:
  grafana_data:

networks:
  app_network:
