{
 "title": "default",
 "description": "The default dashboard.",
 "time": { "from": "2024-12-02T01:21:09.496Z", "to": "2024-12-02T01:51:09.496Z" },
 "panels": [
  {
   "title": "Latency of All Models over Past 15 Minutes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (model) (rate(inference_latency_seconds_sum[1m])) / sum by (model) (rate(inference_latency_seconds_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inference Confidence for Both Model over Last 15 Minutes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "inference_confidence{model=\"Both Model\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inference Confidence for Cognizant Model over Last 15 Minutes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "inference_confidence{model=\"Hand-Cognizant Model\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inference Confidence for Agnostic Model over Last 15 Minutes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "inference_confidence{model=\"Hand-Agnostic Model\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Feedback Count by Type in Past 15 Minutes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 16 },
   "targets": [
    {
     "expr": "sum by (feedback_type) (feedback_count_total)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}