name: CI/CD for Docker Compose

on:
  push:
    branches:
      - main  # Run workflow on pushes to the main branch
  pull_request:
    branches:
      - main  # Run workflow on pull requests targeting the main branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Install Docker Compose
      - name: Install Docker Compose
        run: sudo apt-get install docker-compose

      # Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Build Docker Compose services
      - name: Build Docker Compose
        run: |
          docker-compose -f deployment/docker-compose.yml build

      # Start services in detached mode
      - name: Start Docker Compose Services
        run: |
          docker-compose -f deployment/docker-compose.yml up -d

      # Wait for services to be healthy
      - name: Wait for Health Checks
        run: |
          echo "Waiting for all services to become healthy..."
          MAX_RETRIES=10
          RETRY_INTERVAL=10
          RETRIES=0

          while [ $RETRIES -lt $MAX_RETRIES ]; do
            STATUS=$(docker-compose -f deployment/docker-compose.yml ps | grep "starting")
            if [ -z "$STATUS" ]; then
              echo "All services are healthy!"
              break
            fi
            echo "Services are still starting. Retrying in $RETRY_INTERVAL seconds..."
            RETRIES=$((RETRIES + 1))
            sleep $RETRY_INTERVAL
          done

          if [ $RETRIES -eq $MAX_RETRIES ]; then
            echo "Timeout: Some services did not become healthy in time."
            docker-compose -f deployment/docker-compose.yml ps
            exit 1
          fi

      # Stop services after health checks
      - name: Stop Docker Compose Services
        run: |
          docker-compose -f deployment/docker-compose.yml down
